# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Execute Setup Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test-init-and-validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install project as a package
      run: |
        pip install .
    - name: Test installation
      run: |
        pyengine init example "my game"
    - name: Test created files
      working-directory: ./example
      run: |
        ls
        pyengine validate
    - name: Test build process
      run: |
        pyengine build --output dist
    - name: Check folder contents
      working-directory: ./example/dist
      run: |
        files=("my game") # Add your file paths here
        for file in "${files[@]}"
        do
          if test -f "$file"; then
            echo "$file exists."
          else
            echo "$file does not exist."
            exit 1
          fi
        done
